name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # platform: [linux/amd64, linux/arm64]
        platform: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98
        # with:
        #   driver-opts: 'image=moby/buildkit:v0.10.5'

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GHCR_TOKEN }}

      # - name: Build and push Docker image to Github Repo as matrix
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/multiplatform-app-${{ matrix.platform }}:latest
      #     # platforms: ${{ matrix.platform }}
      #     platforms: linux/${{ matrix.platform }}
          
      # - name: Build and push Docker image to Github Repo as multiplatform
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: ghcr.io/${{ github.repository_owner }}/multiplatform-app:latest
      #     platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub as multiplatform
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/github:latest

      # # Matrix
      # - name: Build and push to Docker Hub as matrix
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-${{ matrix.platform }}:latest
      #     platforms: linux/${{ matrix.platform }}
